### ISSUE TITLE
best error rate

### ISSUE THREAD

**Issue by lhang33** [jackaduma/LAS_Mandarin_PyTorch#1]
Firstly, thanks for your share! I've been looking for an implement on ASR using RNNs+Attention/Transformer, just like the translation implements. 
Could you please tell us your best error rate using these codes you uploaded? Thanks.

**Comment by jackaduma** [comment]
On testset, the CER is about 16%.  I only used aishell-speech-dataset, it's not large. you can find more datasets for training. I think it will be better.
The LAS model is an  excellent ASR solution for offline-ASR

**Comment by lhang33** [comment]
Yes, I also got CER 17% using your code and the aishell dataset after around 300 steps, now training with a mixed dataset which contain larger sets to see if it improves.
By the way, function '"read_text" in aishell.py script runs too slow. I think you can create a dict object by reading the transcript file once, and use the dict to get corresponding texts for the wav paths. I have tried this way and it takes only 10 or 20 secs for getting train-set's (text, wav_path) pair list, using 1 thread.

**Comment by deeplearning00** [comment]
loading data is too slow

**Comment by Aksh97** [comment]
Hi @lhang33, did you got any better results from the training?

if possible, can you share the model?
